### ISSUE TITLE
Add new block in admin dashboard

### ISSUE THREAD

**Issue by k0neko** [pierre-vassoilles/symfony2-sonata-base-project#2]
Hi ^o^ I'm looking for adding a new block in the admin dashboard :/

**Comment by pierre-vassoilles** [comment]
Hi !

First, you should use the **branch intuitiv_skeleton_sf3** for new projects. The master branch is not up to date yet.

For new blocs in Sonata's dashboard, I invite you to read the Sonata's website documentation, there : [https://sonata-project.org/bundles/block/master/doc/reference/your_first_block.html](https://sonata-project.org/bundles/block/master/doc/reference/your_first_block.html)

If you want an example of simple dashboard block, **you can inspire you of this** : [https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Block/AdminStatsBlockService.php](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Block/AdminStatsBlockService.php)

**And for the configuration :** 
- Configure your block service in Symfony (using services.yml or XML or whatever you want)
- In the config.yml file, add : 
```
sonata_block:
    blocks:
        # Other blocks...
        # ...
        your.block.service.name: # Don't forget the ':'

sonata_admin:
    # ...
    dashboard:
        blocks:
            # display a dashboard block - Example for Stats block
            -
                class:    'col-lg-3 col-xs-6'                          # twitter bootstrap responsive code
                position: 'top'                                             # zone in the dashboard
                type:     your.block.service.name               # block id - defined previously in sonata_block config
                settings:
                    code:  sonata.admin.my_admin_class   # admin code - service id
                    icon:  'fa-envelope'                                 # font awesome icon
                    text:  'The stats title text'
                    color: 'bg-yellow'                                    # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        unread: { value: true }
```

**At the end, for the template, you should see this :** 
[https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Block/block_stats.html.twig](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Block/block_stats.html.twig)
